# Generated by Django 3.0.8 on 2020-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.TextField(verbose_name='Путь или ссылка на изображение')),
                ('url', models.TextField(verbose_name='Ссылка')),
                ('cost_from', models.IntegerField(verbose_name='Стоимость от')),
                ('cost_to', models.IntegerField(verbose_name='Стоимость до')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
